# Generated by Django 4.0.3 on 2022-03-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_company', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('score', models.FloatField(null=True)),
                ('datetime', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.companies')),
            ],
            options={
                'unique_together': {('employee_id', 'question_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='TypeResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_response', models.CharField(max_length=15)),
                ('answer_id', models.IntegerField()),
                ('answer_string', models.CharField(max_length=25)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('type_company', models.CharField(max_length=3)),
                ('result', models.FloatField()),
                ('active', models.CharField(max_length=6)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.category')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.formularios')),
                ('type_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.typeresponses')),
            ],
        ),
    ]
