# Generated by Django 3.2.12 on 2022-03-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'unique_together': {('category_id', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('type_response', models.CharField(max_length=15, unique=True)),
                ('response_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'unique_together': {('type_response', 'response_id')},
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('type_company', models.CharField(max_length=8)),
            ],
            options={
                'unique_together': {('company_id', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=140, unique=True)),
                ('type_response_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('question_id', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('type_company', models.CharField(max_length=8)),
                ('result', models.FloatField()),
                ('active', models.CharField(max_length=6)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.category')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.questions')),
                ('type_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.categorymaster', to_field='type_response')),
            ],
        ),
        migrations.CreateModel(
            name='TypeResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('answer_string', models.CharField(max_length=25)),
                ('score', models.FloatField(null=True)),
                ('type_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.categorymaster', to_field='type_response')),
            ],
            options={
                'unique_together': {('type_response', 'answer_id', 'score')},
            },
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('answer_id', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.companies')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack_communication.questions')),
            ],
            options={
                'unique_together': {('employee_id', 'question_id', 'company_id', 'datetime')},
            },
        ),
    ]
