# Generated by Django 3.2.12 on 2022-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
