# Generated by Django 4.0.3 on 2022-03-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack_communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formularios',
            unique_together=set(),
        ),
    ]
